spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:jackson
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  mail:
    host: smtp.gmail.com
    port: 587
    username: "mcyoo247@gmail.com"
    password: "bxnfvggrvpvuqydw"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true